name: Build
on:
  push:
    branches:
      - master
      - release
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # #---------------SERENITY BDD TEST------------------#
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build