name: Build
on:
  push:
    branches:
      - master
      - release
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # #---------------SERENITY BDD TEST------------------#
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x ./InstallChrome.sh
           ./InstallChrome.sh
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew # give permission to Gradle to run the commands
      - name: Build with Gradle
        run: gradle clean test
      - name: Archive Rest Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: GradleReports/emailable-report.html